# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Message(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, descripcion: str=None):  # noqa: E501
        """Message - a model defined in Swagger

        :param code: The code of this Message.  # noqa: E501
        :type code: str
        :param descripcion: The descripcion of this Message.  # noqa: E501
        :type descripcion: str
        """
        self.swagger_types = {
            'code': str,
            'descripcion': str
        }

        self.attribute_map = {
            'code': 'code',
            'descripcion': 'descripcion'
        }

        self._code = code
        self._descripcion = descripcion

    @classmethod
    def from_dict(cls, dikt) -> 'Message':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Message of this Message.  # noqa: E501
        :rtype: Message
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this Message.


        :return: The code of this Message.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this Message.


        :param code: The code of this Message.
        :type code: str
        """

        self._code = code

    @property
    def descripcion(self) -> str:
        """Gets the descripcion of this Message.


        :return: The descripcion of this Message.
        :rtype: str
        """
        return self._descripcion

    @descripcion.setter
    def descripcion(self, descripcion: str):
        """Sets the descripcion of this Message.


        :param descripcion: The descripcion of this Message.
        :type descripcion: str
        """

        self._descripcion = descripcion
